# Generated by Django 4.2.30 on 2026-05-29 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Etkinlik Başlığı')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Etkinlik Yeri')),
                ('start_datetime', models.DateTimeField(verbose_name='Başlangıç Zamanı')),
                ('end_datetime', models.DateTimeField(verbose_name='Bitiş Zamanı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'calendar_events',
                'ordering': ['start_datetime'],
            },
        ),
    ]
