# Generated by Django 4.2.30 on 2026-05-27 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_message', models.TextField(verbose_name='Kullanıcının Sorusu')),
                ('ai_response', models.TextField(verbose_name='Yapay Zeka Yanıtı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Mesaj Tarihi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sohbet Mesajı',
                'verbose_name_plural': 'Sohbet Mesajları',
                'ordering': ['created_at'],
            },
        ),
    ]
