# Generated by Django 5.2.14 on 2026-05-24 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailysummary',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='dailysummary',
            name='city',
            field=models.CharField(default='Istanbul', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailysummary',
            name='pollen',
            field=models.CharField(default='Normal', max_length=50),
        ),
        migrations.AddField(
            model_name='dailysummary',
            name='temp',
            field=models.FloatField(default=20.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailysummary',
            name='weather_type',
            field=models.CharField(default='Clear', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailysummary',
            name='risk_level',
            field=models.CharField(default='Düşük', max_length=20),
        ),
        migrations.AlterField(
            model_name='dailysummary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to=settings.AUTH_USER_MODEL),
        ),
    ]
