# Generated by Django 4.2.30 on 2026-05-29 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('summary', '0002_alter_dailysummary_options_dailysummary_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255, verbose_name='Yapılan İşlem')),
                ('details', models.TextField(verbose_name='İşlem Detayları')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Adresi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'system_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
