# Generated by Django 4.2.30 on 2026-05-29 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0003_systemlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_disease', models.CharField(blank=True, max_length=255, null=True, verbose_name='Hedef Hastalık Filtresi')),
                ('title', models.CharField(max_length=255, verbose_name='Bildirim Başlığı')),
                ('message', models.TextField(verbose_name='Bildirim İçeriği')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'system_notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
