# Generated by Django 4.2.30 on 2026-05-29 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0004_systemnotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemnotification',
            name='target_disease',
        ),
        migrations.AddField(
            model_name='systemnotification',
            name='filter_type',
            field=models.CharField(default='all', max_length=50, verbose_name='Filtre Tipi'),
        ),
        migrations.AddField(
            model_name='systemnotification',
            name='filter_value',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Filtre Değeri'),
        ),
    ]
