# Generated by Django 5.2.14 on 2026-05-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_name', models.CharField(max_length=100)),
                ('trigger_factor', models.CharField(max_length=100)),
                ('recommendation', models.TextField()),
            ],
        ),
    ]
